server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('slides.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

slides/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views
from . import api_views


def slugs(*args):
    return tuple(r'(?P<%s_slug>[\w\-]+)' % (a,) for a in args)


router = routers.DefaultRouter()
router.register(r'slide-data', api_views.SlideViewSet)
router.register(r'annotations/(?P<slide_pk>\d+)', api_views.AnnotationViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),

    url(r'^$', views.index),
    url(r'^%s/%s$' % slugs('course', 'deck'), views.deck),
    url(r'^%s/%s/%s$' % slugs('course', 'deck', 'slide'), views.deck),
]

slides/models.py
from django.db import models
from autoslug import AutoSlugField
from jsonfield import JSONField
from django.conf import settings
from django.db import transaction
from django.db.models import Max
from django.utils import timezone
from django.utils.safestring import mark_safe

STATUS_CHOICES = [
    ('A', 'Active'),
    ('D', 'Deleted'),
]

class Course(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)
    slug = AutoSlugField(populate_from='name', max_length=20, unique=True, db_index=True)
    data = JSONField(default=dict)

    def __str__(self):
        return self.name


class Deck(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=False, blank=False)
    slug = AutoSlugField(populate_from='name', max_length=20, unique_with=['course'], db_index=True)
    order = models.PositiveSmallIntegerField(null=False)
    status = models.CharField(max_length=1, null=False, blank=False, choices=STATUS_CHOICES, default='A')
    data = JSONField(default=dict)

    class Meta:
        unique_together = (('course', 'order'),)
        ordering = ['order']

    def __str__(self):
        return self.course.name + ': ' + self.name


class Slide(models.Model):
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=False, blank=False)
    slug = AutoSlugField(populate_from='title', max_length=20, unique_with=['deck'], db_index=True)
    order = models.PositiveSmallIntegerField(null=False)
    content = models.TextField()
    status = models.CharField(max_length=1, null=False, blank=False, choices=STATUS_CHOICES, default='A')
    data = JSONField(default=dict)

    class Meta:
        unique_together = (('deck', 'order'),)
        ordering = ['order']

    def __str__(self):
        return str(self.title)

    def as_html(self):
        return mark_safe(self.content)

class Annotation(models.Model):
    slide = models.ForeignKey(Slide, on_delete=models.CASCADE, related_name='annotations')
    order = models.PositiveSmallIntegerField(null=False)
    status = models.CharField(max_length=1, null=False, blank=False, choices=STATUS_CHOICES, default='A')
    data = JSONField(default=dict)
    # data  ::= {"elements": [elementObj*]}
    # elementObj ::= pathObj
    # pathObj ::= {"elt": "path", "pointsX": [float], "pointsY: [float]}

    class Meta:
        unique_together = (('slide', 'order'),)
        ordering = ['order']

    def save(self, *args, **kwargs):
        with transaction.atomic():
            if not self.order:
                maxorder = Annotation.objects.filter(slide_id=self.slide_id).aggregate(Max('order'))['order__max']
                if maxorder is None:
                    self.order = 1
                else:
                    self.order = maxorder + 1

            super(Annotation, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # soft delete so we can redo an undo.
        self.status = 'D'
        self.save()


class SlideShow(models.Model):
    """
    Object representing an ongoing slide show.

    May be deleted when show ends (or last_touch indicates it's stale).
    """
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    current_slide = models.ForeignKey(Slide, on_delete=models.CASCADE)
    last_touch = models.DateTimeField(null=False, blank=False, default=timezone.now)
    data = JSONField(default=dict)

slides/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Deck, Slide


def index(request):
    decks = Deck.objects.all()
    context = {
        'decks': decks,
    }
    return render(request, 'slides/index.html', context=context)


def deck(request, course_slug, deck_slug, slide_slug=None):
    deck = get_object_or_404(Deck, course__slug=course_slug, slug=deck_slug)
    if slide_slug:
        slide = get_object_or_404(Slide, deck=deck, slug=slide_slug)
    else:
        slide = get_list_or_404(Slide, deck=deck)[0]

    context = {
        'deck': deck,
        'slide': slide,
    }
    return render(request, 'slides/deck.html', context=context)

slides/templates/slides/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>{% block title %}Slides{% endblock %}</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.css" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400,700|Source+Sans+Pro:400,400italic,700,700italic" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'slide-style.css' %}" />
{% block headextra %}{% endblock %}
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

slides/templates/slides/deck.html
{% extends "slides/base.html" %}
{% load staticfiles %}
{% load compress %}

{% block headextra %}
<script>
var slide_pk = "{{ slide.pk|escapejs }}";
var csrf_token = "{{ csrf_token|escapejs }}";
var presenter = true;
</script>
{% endblock %}

{% block title %}{{ deck.course.name }}: {{ deck.name }}{% endblock %}

{% block content %}
<main id="slide-container"></main>

{% compress js %}
<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'react/dist/react.min.js' %}"></script>
<script src="{% static 'react-dom/dist/react-dom.min.js' %}"></script>
<script src="{% static 'config.js' %}"></script>
{% endcompress %}
{% compress js %}
<!--script type="text/jsx" src="{% static 'react-logic.js' %}"></script-->
{% endcompress %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
<script type="text/babel" src="{% static 'react-logic.js' %}"></script>

{% endblock %}

slides/templates/slides/index.html
{% extends "slides/base.html" %}

{% block title %}Slides{% endblock %}

{% block content %}
<h1>Slides</h1>
<ul>
{% for deck in decks %}
<li><a href="{% url 'slides.views.deck' course_slug=deck.course.slug deck_slug=deck.slug %}">{{ deck }}</a>
  <ul>
  {% for slide in deck.slide_set.all %}
    <li><a href="{% url 'slides.views.deck' course_slug=deck.course.slug deck_slug=deck.slug slide_slug=slide.slug %}">{{ slide }}</a></li>
  {% endfor %}
  </ul>
</li>
{% endfor %}
</ul>

{% endblock %}